name: Format Python Code

on:
  pull_request:
    branches: [ main ]  # Adjust branch as needed

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Format with Black
      run: |
        black ./functions.py
        black ./main.py
      

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply Black formatting"
        file_pattern: |
          ./main.py
          ./functions.py
